name: pre-commit-checks

# Controls when the workflow will run
on:
  pull_request:
    # Trigger workflow on PR creation, updates, and reopening
    types: [opened, synchronize, reopened]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:

      # Debug step to output information about the current pull request
      - name: Debug Information
        run: |
          echo "Actor: $GITHUB_ACTOR"
          echo "Target ref (base branch): $GITHUB_BASE_REF"
          echo "Pull request ref (head branch): $GITHUB_HEAD_REF"
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Event name: $GITHUB_EVENT_NAME"
          echo "Ref: $GITHUB_REF"
          echo "SHA of current commit: $GITHUB_SHA"
          echo "Workflow run ID: $GITHUB_RUN_ID"
          echo "Commit message: $(git log -1 --pretty=%B)"
          echo "Main branch (default branch): $(git symbolic-ref refs/remotes/origin/HEAD)"
          echo "Is this a pull request? ${{ github.event.pull_request != null }}"
          echo "Actor: $GITHUB_ACTOR"
          echo "Target ref (base branch): $GITHUB_BASE_REF"
          echo "Pull request ref (head branch): $GITHUB_HEAD_REF"
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Event name: $GITHUB_EVENT_NAME"
          echo "Ref: $GITHUB_REF"
          echo "SHA of current commit: $GITHUB_SHA"
          echo "Workflow run ID: $GITHUB_RUN_ID"
          echo "Commit message: $(git log -1 --pretty=%B)"
          echo "Main branch (default branch): $(git symbolic-ref refs/remotes/origin/HEAD)"
          echo "Is this a pull request? ${{ github.event.pull_request != null }}"
